version: '3.8'

services:
  vvtde:
    build:
      context: .
    image: flexlug/vvtde:latest
    restart: always
    environment:
      # URI для подключения к БД
      "DbConnection": "Data Source=videos.db"
      # Директория, где хранится БД
      "DbFoler": "db"
      # Название исполняемого файла yt-dlp
      "YtDlpPath": "yt-dlp_linux"
      # Директория, в которой будут сохранаться видео
      "VideoDownloadPath": "static"
      # Токен, необходимый для доступа к Endpoint-ам FetchVideo и RequestDownload
      "Token": "SecretToken"
    volumes:
      # Директория для загруженных видео
      - /your/path/to/static:/app/static/
      # Директория, где хранится БД
      - ./db:/app/db